export const GET_STATISTIC_PER_YEAR = 'GET_STATISTIC_PER_YEAR'
export const GET_STATISTIC_PER_YEAR_SUCCESS = 'GET_STATISTIC_PER_YEAR_SUCCESS'
export const GET_STATISTIC_PER_YEAR_FAIL = 'GET_STATISTIC_PER_YEAR_FAIL'

export const GET_STATISTIC_ADMIN_PER_MONTH = 'GET_STATISTIC_ADMIN_PER_MONTH'
export const GET_STATISTIC_ADMIN_PER_MONTH_SUCCESS = 'GET_STATISTIC_ADMIN_PER_MONTH_SUCCESS'
export const GET_STATISTIC_ADMIN_PER_MONTH_FAIL = 'GET_STATISTIC_ADMIN_PER_MONTH_FAIL'

export const GET_STATISTIC_ADMIN_PER_YEAR = 'GET_STATISTIC_ADMIN_PER_YEAR'
export const GET_STATISTIC_ADMIN_PER_YEAR_SUCCESS = 'GET_STATISTIC_ADMIN_PER_YEAR_SUCCESS'
export const GET_STATISTIC_ADMIN_PER_YEAR_FAIL = 'GET_STATISTIC_ADMIN_PER_YEAR_FAIL'