export const GET_TOUR = 'GET_TOUR'
export const GET_TOUR_SUCCESS = 'GET_TOUR_SUCCESS'
export const GET_TOUR_FAIL = 'GET_TOUR_FAIL'

export const ADD_TOUR = 'ADD_TOUR'
export const ADD_TOUR_SUCCESS = 'ADD_TOUR_SUCCESS'
export const ADD_TOUR_FAIL = 'ADD_TOUR_FAIL'

export const DELETE_TOUR = 'DELETE_TOUR'
export const DELETE_TOUR_SUCCESS = 'DELETE_TOUR_SUCCESS'
export const DELETE_TOUR_FAIL = 'DELETE_TOUR_FAIL'

export const GET_TOUR_DOMESTIC = 'GET_TOUR_DOMESTIC' 
export const GET_TOUR_DOMESTIC_SUCCESS = 'GET_TOUR_DOMESTIC_SUCCESS' 
export const GET_TOUR_DOMESTIC_FAIL = 'GET_TOUR_DOMESTIC_FAIL' 

export const GET_TOUR_INTERNATIONAL = 'GET_TOUR_INTERNATIONAL' 
export const GET_TOUR_INTERNATIONAL_SUCCESS = 'GET_TOUR_INTERNATIONAL_SUCCESS' 
export const GET_TOUR_INTERNATIONAL_FAIL = 'GET_TOUR_INTERNATIONAL_FAIL' 

export const FILTER_TOUR = 'FILTER_TOUR' 
export const FILTER_TOUR_SUCCESS = 'FILTER_TOUR_SUCCESS' 
export const FILTER_TOUR_FAIL = 'FILTER_TOUR_FAIL' 

export const GET_OUTSTANDING_TOUR = 'GET_OUTSTANDING_TOUR' 
export const GET_OUTSTANDING_TOUR_SUCCESS = 'GET_OUTSTANDING_TOUR_SUCCESS' 
export const GET_OUTSTANDING_TOUR_FAIL = 'GET_OUTSTANDING_TOUR_FAIL' 

export const GET_TOUR_DETAIL = 'GET_TOUR_DETAIL' 
export const GET_TOUR_DETAIL_SUCCESS = 'GET_TOUR_DETAIL_SUCCESS' 
export const GET_TOUR_DETAIL_FAIL = 'GET_TOUR_DETAIL_FAIL' 
