export const ROUTE_ADD_TOUR = '/owner/add-tour'
export const ROUTE_LIST_TOUR = '/owner/list-tour'
export const ROUTE_LIST_TICKET = '/owner/list-ticket'
export const ROUTE_LIST_CUSTOMER = '/owner/list-customer'
export const ROUTE_OWNER_ACCOUNT = '/owner/acount'
