export const SET_ACCOUNT_INFO = 'SET_ACCOUNT_INFO'
export const RESET_ACCOUNT_INFO = 'RESET_ACCOUNT_INFO'

export const GET_USER_OWNER = 'GET_USER_OWNER'
export const GET_USER_OWNER_SUCCESS = 'GET_USER_OWNER_SUCCESS'
export const GET_USER_OWNER_FAIL = 'GET_USER_OWNER_FAIL'