export const SET_ACCOUNT_INFO = 'SET_ACCOUNT_INFO'
export const RESET_ACCOUNT_INFO = 'RESET_ACCOUNT_INFO'

export const GET_USER_OWNER = 'GET_USER_OWNER'
export const GET_USER_OWNER_SUCCESS = 'GET_USER_OWNER_SUCCESS'
export const GET_USER_OWNER_FAIL = 'GET_USER_OWNER_FAIL'

export const GET_CUSTOMER_ADMIN = 'GET_CUSTOMER_ADMIN'
export const GET_CUSTOMER_ADMIN_SUCCESS = 'GET_CUSTOMER_ADMIN_SUCCESS'
export const GET_CUSTOMER_ADMIN_FAIL = 'GET_CUSTOMER_ADMIN_FAIL'

export const GET_OWNER_ADMIN = 'GET_OWNER_ADMIN'
export const GET_OWNER_ADMIN_SUCCESS = 'GET_OWNER_ADMIN_SUCCESS'
export const GET_OWNER_ADMIN_FAIL = 'GET_OWNER_ADMIN_FAIL'

export const BECOME_OWNER = 'BECOME_OWNER'
export const BECOME_OWNER_SUCCESS = 'BECOME_OWNER_SUCCESS'
export const BECOME_OWNER_FAIL = 'BECOME_OWNER_FAIL'

export const SET_ACTIVE_OWNER = 'SET_ACTIVE_OWNER'
export const SET_ACTIVE_OWNER_SUCCESS = 'SET_ACTIVE_OWNER_SUCCESS'
export const SET_ACTIVE_OWNER_FAIL = 'SET_ACTIVE_OWNER_FAIL'