export const GET_TYPEPLACE = 'GET_TYPEPLACE'
export const GET_TYPEPLACE_SUCCESS = 'GET_TYPEPLACE_SUCCESS'
export const GET_TYPEPLACE_FAIL = 'GET_TYPEPLACE_FAIL'

export const CREATE_TYPEPLACE = 'CREATE_TYPEPLACE'
export const CREATE_TYPEPLACE_SUCCESS = 'CREATE_TYPEPLACE_SUCCESS'
export const CREATE_TYPEPLACE_FAIL = 'CREATE_TYPEPLACE_FAIL'

export const UPDATE_TYPEPLACE = 'UPDATE_TYPEPLACE'
export const UPDATE_TYPEPLACE_SUCCESS = 'UPDATE_TYPEPLACE_SUCCESS'
export const UPDATE_TYPEPLACE_FAIL = 'UPDATE_TYPEPLACE_FAIL'

export const DELETE_TYPEPLACE = 'DELETE_TYPEPLACE'
export const DELETE_TYPEPLACE_SUCCESS = 'DELETE_TYPEPLACE_SUCCESS'
export const DELETE_TYPEPLACE_FAIL = 'DELETE_TYPEPLACE_FAIL'