export const GET_TICKET = 'GET_TICKET'
export const GET_TICKET_SUCCESS = 'GET_TICKET_SUCCESS'
export const GET_TICKET_FAIL = 'GET_TICKET_FAIL'

export const GET_TICKET_PER_TOUR = 'GET_TICKET_PER_TOUR'
export const GET_TICKET_PER_TOUR_SUCCESS = 'GET_TICKET_PER_TOUR_SUCCESS'
export const GET_TICKET_PER_TOUR_FAIL = 'GET_TICKET_PER_TOUR_FAIL'

export const DELETE_TICKET = 'DELETE_TICKET'
export const DELETE_TICKET_SUCCESS = 'DELETE_TICKET_SUCCESS'
export const DELETE_TICKET_FAIL = 'DELETE_TICKET_FAIL'

export const RESET_TICKET = 'RESET_TICKET'

export const SET_COMPLETE_TICKET = 'SET_COMPLETE_TICKET'
export const SET_COMPLETE_TICKET_SUCCESS = 'SET_COMPLETE_TICKET_SUCCESS'
export const SET_COMPLETE_TICKET_FAIL = 'SET_COMPLETE_TICKET_FAIL'