export const GET_TICKET = 'GET_TICKET'
export const GET_TICKET_SUCCESS = 'GET_TICKET_SUCCESS'
export const GET_TICKET_FAIL = 'GET_TICKET_FAIL'

export const DELETE_TICKET = 'DELETE_TICKET'
export const DELETE_TICKET_SUCCESS = 'DELETE_TICKET_SUCCESS'
export const DELETE_TICKET_FAIL = 'DELETE_TICKET_FAIL'