export const GET_NEWS_LIST = 'GET_NEWS'
export const GET_NEWS_LIST_SUCCESS = 'GET_NEWS_SUCCESS'
export const GET_NEWS_LIST_FAIL = 'GET_NEWS_FAIL'

export const GET_NEWS_DETAIL = 'GET_NEWS_DETAIL' 
export const GET_NEWS_DETAIL_SUCCESS = 'GET_NEWS_DETAIL_SUCCESS' 
export const GET_NEWS_DETAIL_FAIL = 'GET_NEWS_DETAIL_FAIL' 

export const GET_NEWS_COMPANY = 'GET_NEW_COMPANY' 
export const GET_NEWS_COMPANY_SUCCESS = 'GET_NEWS_COMPANY_SUCCESS' 
export const GET_NEWS_COMPANY_FAIL = 'GET_NEWS_COMPANY_FAIL'

export const DELETE_NEWS = 'DELETE_NEWS'
export const DELETE_NEWS_SUCCESS = 'DELETE_NEWS_SUCCESS'
export const DELETE_NEWS_FAIL = 'DELETE_NEWS_FAIL'

export const UPDATE_NEWS = 'UPDATE_NEWS'
export const UPDATE_NEWS_SUCCESS = 'UPDATE_NEWS_SUCCESS'
export const UPDATE_NEWS_FAIL = 'UPDATE_NEWS_FAIL'

export const CREATE_NEWS = 'CREATE_NEWS'
export const CREATE_NEWS_SUCCESS = 'CREATE_NEWS_SUCCESS'
export const CREATE_NEWS_FAIL = 'CREATE_NEWS_FAIL'